pipeline {
       agent any
       stages {
           stage('Build') {
                steps {
                    echo 'Running build automation poc'
                       }
                  
                           }
            stage('DeployToDev') {
               steps {
                kubernetesDeploy{
                    kubeconfigId: 'kubeconfig',
                    configs: 'create-namespace.yaml',
                    enableConfigSubstitution: true
            }
                }
         }
