pipeline {
       agent any
       stages {
           stage('Build') {
                steps {
                    echo 'Running build automation poc'
                       }
                  
                           }
            stage('DeployToDev') {
               steps {
                echo 'Running deploy automation poc'
            }
                }
         }
